#!/usr/bin/env bash
# bash script to nginx on server
sudo apt-get -y update && sudo apt-get install -y nginx

ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
sudo service nginx start 
