#!/usr/bin/env bash
# This script is displaying "Holberton School" 20 times
number=1

while ((number < 21 ))
do
        echo $number

    case $number in
	    4)
	        echo "bad luck from China";;
	    9)
	        echo "bad luck from Japan";;
	    17)
	        echo "bad luck from Italy";;
    esac
    ((number++))
done